 code --list-extensions | xargs -L 1 echo code --install-extension
code --install-extension alex-pex.theme-darkula
code --install-extension christian-kohler.npm-intellisense
code --install-extension christian-kohler.path-intellisense
code --install-extension CraigMaslowski.erb
code --install-extension dariofuzinato.vue-peek
code --install-extension daylerees.rainglow
code --install-extension dbaeumer.vscode-eslint
code --install-extension eg2.vscode-npm-script
code --install-extension esbenp.prettier-vscode
code --install-extension formulahendry.auto-close-tag
code --install-extension formulahendry.auto-rename-tag
code --install-extension gerane.Theme-Darksidelightselection
code --install-extension gerane.Theme-FlatlandMonokai
code --install-extension karyfoundation.theme-karyfoundation-themes
code --install-extension kondratiev.sshextension
code --install-extension liximomo.sftp
code --install-extension ms-vscode.Go
code --install-extension mubaidr.vuejs-extension-pack
code --install-extension octref.vetur
code --install-extension robinbentley.sass-indented
code --install-extension sashaweiss.bracket-jumper
code --install-extension seedess.vscode-remote-editor
code --install-extension sianglim.slim
code --install-extension tombonnike.vscode-status-bar-format-toggle
code --install-extension vortizhe.simple-ruby-erb
code --install-extension vscodevim.vim
code --install-extension waderyan.gitblame
code --install-extension xabikos.JavaScriptSnippets
